{% set name = "django-prose" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/django_prose/django_prose-{{ version }}.tar.gz
  sha256: 000c554496c2f61358c2602e21b54677bb02a727662ec9783dba5e35acfe4af8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry >=0.12
    - python {{ python_min }}
  run:
    - bleach >=4.0
    - django >=3.2
    - python >={{ python_min }},<4.0

test:
  imports:
    - prose
    - prose.migrations
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/withlogicco/django-prose
  summary: Rich text editing for Django projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
