{% set name = "django-prose" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/django_prose/django_prose-{{ version }}.tar.gz
  sha256: ee287edaf011dd27b967f9e7c304557c0de907d5902ec942a2e30bf32ad50712

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry >=0.12
    - python >=3.8,<4.0
  run:
    - bleach >=4.0
    - django >=3.2
    - python >=3.8,<4.0

test:
  imports:
    - prose
    - prose.migrations
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/withlogicco/django-prose
  summary: Rich text editing for Django projects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
